Fix mtf broadcast error when lowering
We don't need to add the temporary dimensions to tensors before broadcasting them

This fixes:
ValueError: No new dimensions allowed in output input_shapes = [[Dimension(name='batch', size=256), Dimension(name='sequence', size=128)]] output_shape= [Dimension(name='dummy_batch', size=1), Dimension(name='sequence', size=128)]